// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUDNoolzNDvnWX1Do07C2zMHk4qI9oqI',
    appId: '1:539304915494:web:3599d9e13b4433955cace7',
    messagingSenderId: '539304915494',
    projectId: 'healthapp-e68ad',
    authDomain: 'healthapp-e68ad.firebaseapp.com',
    storageBucket: 'healthapp-e68ad.firebasestorage.app',
    measurementId: 'G-WNPM1BF51L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2vKDfGWR9iZnOW0EcEGpOer2qc6j3zE',
    appId: '1:539304915494:android:d7cd07f3c0bf4b9e5cace7',
    messagingSenderId: '539304915494',
    projectId: 'healthapp-e68ad',
    storageBucket: 'healthapp-e68ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBred81d4WAqVTVfrCEjZT9npPNvwGIW78',
    appId: '1:539304915494:ios:9dee5ace6518db845cace7',
    messagingSenderId: '539304915494',
    projectId: 'healthapp-e68ad',
    storageBucket: 'healthapp-e68ad.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBred81d4WAqVTVfrCEjZT9npPNvwGIW78',
    appId: '1:539304915494:ios:9dee5ace6518db845cace7',
    messagingSenderId: '539304915494',
    projectId: 'healthapp-e68ad',
    storageBucket: 'healthapp-e68ad.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIUDNoolzNDvnWX1Do07C2zMHk4qI9oqI',
    appId: '1:539304915494:web:a5fa464a6f6c63815cace7',
    messagingSenderId: '539304915494',
    projectId: 'healthapp-e68ad',
    authDomain: 'healthapp-e68ad.firebaseapp.com',
    storageBucket: 'healthapp-e68ad.firebasestorage.app',
    measurementId: 'G-14VBF2FB00',
  );
}
